// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.0
// source: subscriber.proto

package subscriber

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformSubscriber_Subscribe_FullMethodName      = "/platform_subscriber.PlatformSubscriber/Subscribe"
	PlatformSubscriber_Heartbeat_FullMethodName      = "/platform_subscriber.PlatformSubscriber/Heartbeat"
	PlatformSubscriber_Unsubscribe_FullMethodName    = "/platform_subscriber.PlatformSubscriber/Unsubscribe"
	PlatformSubscriber_GetActiveCount_FullMethodName = "/platform_subscriber.PlatformSubscriber/GetActiveCount"
	PlatformSubscriber_GetActiveList_FullMethodName  = "/platform_subscriber.PlatformSubscriber/GetActiveList"
)

// PlatformSubscriberClient is the client API for PlatformSubscriber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformSubscriberClient interface {
	Subscribe(ctx context.Context, in *Target, opts ...grpc.CallOption) (*OkResponse, error)
	Heartbeat(ctx context.Context, in *Target, opts ...grpc.CallOption) (*OkResponse, error)
	Unsubscribe(ctx context.Context, in *Target, opts ...grpc.CallOption) (*OkResponse, error)
	GetActiveCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetActiveCountResponse, error)
	GetActiveList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetActiveListResponse, error)
}

type platformSubscriberClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformSubscriberClient(cc grpc.ClientConnInterface) PlatformSubscriberClient {
	return &platformSubscriberClient{cc}
}

func (c *platformSubscriberClient) Subscribe(ctx context.Context, in *Target, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, PlatformSubscriber_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformSubscriberClient) Heartbeat(ctx context.Context, in *Target, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, PlatformSubscriber_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformSubscriberClient) Unsubscribe(ctx context.Context, in *Target, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, PlatformSubscriber_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformSubscriberClient) GetActiveCount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetActiveCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveCountResponse)
	err := c.cc.Invoke(ctx, PlatformSubscriber_GetActiveCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformSubscriberClient) GetActiveList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetActiveListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveListResponse)
	err := c.cc.Invoke(ctx, PlatformSubscriber_GetActiveList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformSubscriberServer is the server API for PlatformSubscriber service.
// All implementations must embed UnimplementedPlatformSubscriberServer
// for forward compatibility.
type PlatformSubscriberServer interface {
	Subscribe(context.Context, *Target) (*OkResponse, error)
	Heartbeat(context.Context, *Target) (*OkResponse, error)
	Unsubscribe(context.Context, *Target) (*OkResponse, error)
	GetActiveCount(context.Context, *emptypb.Empty) (*GetActiveCountResponse, error)
	GetActiveList(context.Context, *emptypb.Empty) (*GetActiveListResponse, error)
	mustEmbedUnimplementedPlatformSubscriberServer()
}

// UnimplementedPlatformSubscriberServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformSubscriberServer struct{}

func (UnimplementedPlatformSubscriberServer) Subscribe(context.Context, *Target) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPlatformSubscriberServer) Heartbeat(context.Context, *Target) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPlatformSubscriberServer) Unsubscribe(context.Context, *Target) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedPlatformSubscriberServer) GetActiveCount(context.Context, *emptypb.Empty) (*GetActiveCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveCount not implemented")
}
func (UnimplementedPlatformSubscriberServer) GetActiveList(context.Context, *emptypb.Empty) (*GetActiveListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveList not implemented")
}
func (UnimplementedPlatformSubscriberServer) mustEmbedUnimplementedPlatformSubscriberServer() {}
func (UnimplementedPlatformSubscriberServer) testEmbeddedByValue()                            {}

// UnsafePlatformSubscriberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformSubscriberServer will
// result in compilation errors.
type UnsafePlatformSubscriberServer interface {
	mustEmbedUnimplementedPlatformSubscriberServer()
}

func RegisterPlatformSubscriberServer(s grpc.ServiceRegistrar, srv PlatformSubscriberServer) {
	// If the following call pancis, it indicates UnimplementedPlatformSubscriberServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformSubscriber_ServiceDesc, srv)
}

func _PlatformSubscriber_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformSubscriberServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformSubscriber_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformSubscriberServer).Subscribe(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformSubscriber_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformSubscriberServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformSubscriber_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformSubscriberServer).Heartbeat(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformSubscriber_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformSubscriberServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformSubscriber_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformSubscriberServer).Unsubscribe(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformSubscriber_GetActiveCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformSubscriberServer).GetActiveCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformSubscriber_GetActiveCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformSubscriberServer).GetActiveCount(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformSubscriber_GetActiveList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformSubscriberServer).GetActiveList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformSubscriber_GetActiveList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformSubscriberServer).GetActiveList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformSubscriber_ServiceDesc is the grpc.ServiceDesc for PlatformSubscriber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformSubscriber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_subscriber.PlatformSubscriber",
	HandlerType: (*PlatformSubscriberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _PlatformSubscriber_Subscribe_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _PlatformSubscriber_Heartbeat_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _PlatformSubscriber_Unsubscribe_Handler,
		},
		{
			MethodName: "GetActiveCount",
			Handler:    _PlatformSubscriber_GetActiveCount_Handler,
		},
		{
			MethodName: "GetActiveList",
			Handler:    _PlatformSubscriber_GetActiveList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscriber.proto",
}
